add highlight DAO
cosmofactory/triptip_backend pull request #118
Opened 2024-10-27 08:22 UTC by PavelHightTower

2024-10-27 11:59 UTC, cosmofactory requested changes

2024-10-27 11:59 UTC, cosmofactory commented on src/trips/models.py
> +    __tablename__ = "routees"
?

2024-10-27 11:59 UTC, cosmofactory commented on src/trips/schemas.py
> +class SHighlightOutput(BaseModel):
тут id не хватает

2024-10-27 11:59 UTC, cosmofactory commented on src/trips/services.py
> +    async def create_location(db: AsyncSession, trip_id: int, location_data: SLocationInput):
А зачем ты тут от юзера избавился

2024-10-27 11:59 UTC, cosmofactory commented on src/trips/services.py
> +                raise ValueError("Invalid highlight entity type")
Зачем это? У тебя в SHightLightInput уже есть либо route_id либо location_id, передавай в базу что есть, база разберется с чем связать

2024-10-27 11:59 UTC, cosmofactory commented on src/trips/schemas.py
> +    location_id: int | None
Раз ты поставил правило на уровне БД, что только одно из двух полей может быть заполнено, то давай и для пользователей API тут проверку поставим.

```suggestion
class SHighlightInput(BaseModel):
    """Create new highlight."""

    name: str
    description: str
    route_id: int | None
    location_id: int | None
    
    @model_validator(mode="before")
    @classmethod
    def check_one_parent_present(cls, data: Any):
        route_id, location_id = data.get('route_id'), data.get('location_id')
        if any([route_id is None and location_id is None, route_id is not None and location_id is not None]):
            raise ValueError("Either route_id or location_id must be set, but not both.")
        return data
    
```

2024-10-27 11:59 UTC, cosmofactory commented on src/trips/services.py
> +                highlight = await HighlightDAO.get_object_or_404(db, route_id=entity_id)
У тебя отношение route к highlight one to many. 
То есть ты тянешь Highlight по неуникальному ключу, это вернет тебе список, а не объект.
Судя по названию этого метода, надо тянеть по Highlight.id и не делать проверку на Enum.

2024-10-27 17:20 UTC, PavelHightTower commented on src/trips/models.py
> +    __tablename__ = "routees"
могут стрелять по мне, а заденут вас. случайно

2024-10-27 17:21 UTC, PavelHightTower commented on src/trips/services.py
> +    async def create_location(db: AsyncSession, trip_id: int, location_data: SLocationInput):
@staticmethod
    async def create_location(db: AsyncSession, trip_id: int, location_data: SLocationInput):
        """Create a new location."""
        location_data = location_data.model_dump()
        location_data["trip_id"] = trip_id
        created_location = await LocationDAO.create(db, **location_data)
        return created_location
        
 а у меня подсветило, что он не используется внутри функции я и стер

2024-10-27 17:24 UTC, PavelHightTower commented on src/trips/services.py
> +                raise ValueError("Invalid highlight entity type")
ок, не думал, что это магия так работает

2024-10-28 17:39 UTC, cosmofactory requested changes

2024-10-28 17:39 UTC, cosmofactory commented on src/trips/services.py
> +        created_highlight = await RouteDAO.create(db, **highlight_data)
Create hightlight, при этом мы создаем RouteDAO?

2024-10-28 17:47 UTC, cosmofactory approved these changes

2024-10-28 18:34 UTC, merged