add docker file to build image
cosmofactory/triptip_backend pull request #12
Opened 2024-04-03 06:46 UTC by PavelHightTower

2024-04-03 12:33 UTC, cosmofactory commented on Dockerfile
> +CMD ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
```suggestion
CMD ["poetry", "run", "gunicorn", "src.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicronWorker", "--bind", "0.0.0.0:8000"]
```

2024-04-03 12:33 UTC, cosmofactory commented on README.md
> +docker run -d --name triptip -p 8000:80 triptip:0.1
```suggestion
docker run -d --name triptip -p 8000:8000 triptip:0.1 
```

2024-04-03 19:43 UTC, cosmofactory requested changes
Я бы еще container_name для удобства добавил

2024-04-03 19:43 UTC, cosmofactory commented on docker-compose.yaml
> +  service:
я бы предложил более точный нейминг, типа triptip/app/main/backend
мало ли у нас сервисов будет

2024-04-03 19:43 UTC, cosmofactory commented on Dockerfile
> +CMD ["poetry", "run", "gunicorn", "src.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", \
Мы запускаем через docker-compose, там та же команда, так что здесь ее можно убрать

2024-04-03 19:43 UTC, cosmofactory commented on docker-compose.yaml
> +      - db
```suggestion
      - db
    restart: always
```

2024-04-03 19:43 UTC, cosmofactory commented on docker-compose.yaml
> +      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
У нас асинхронный постгрес, то есть ссылка будет такая `postgresql+asyncpg://`

Но не совсем понимаю зачем она здесь объявлена явно?

2024-04-03 20:03 UTC, cosmofactory commented on docker-compose.yaml
> +
```suggestion
    env_file:
      - .env
```
В дальнейшем мы будем использовать environment variables, типа DEBUG, LOG_LEVE и далее, чтобы каждый раз compose не менять, лучше указать ссылку на файл со всеми переменными
https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-environment-attribute

2024-04-04 06:23 UTC, PavelHightTower commented on docker-compose.yaml
> +      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
окей, если где-то в другом месте объявляется, то ок. это я так по наитию сделал.

2024-04-04 10:21 UTC, cosmofactory approved these changes

2024-04-04 10:21 UTC, merged